### ISSUE TITLE
To-do 1

### ISSUE THREAD

**Issue by Woongyu** [Woongyu/spring-cloud-example#14]
- [x] Board 게시물 생성 시 Parallel하게 난수로 생성할 수 있도록 고민
- [x] 회원에 Grade(등급) 컬럼을 만들어보기
- Grade 생성 시 Enum Class 활용
- 등록 게시물 갯수에 따른 등급 부여, Bronze, Silver...
- [x] 회원 수정 API를 생성하는데, 단건 / 다건 API 각각 생성하기
- 기존 회원 생성 시 Bronze, 회원 수정을 통해 Grade를 업데이트 하는 방식으로 설계
- [ ] Spring Batch 서버를 신규로 생성해서 등급을 갱신하기
- [ ] Batch 수행 시 Feign Client를 사용해볼 수 있도록 설계하기
